package.json, src/components/WalletHistory.vue, src/components/WalletTransactionDetails.vue, src/components/mixins/TransactionMixin.ts, src/index.ts, src/lang/en/index.ts, src/services/subquery/parser.ts, src/services/subquery/queries/historyElements.ts, src/types/rewards.ts, src/util/index.ts, src/util/storage.ts, tests/unit/components/__snapshots__/WalletTransactionDetails.spec.ts.snap, yarn.lock
https://soramitsu.atlassian.net/browse/PW-388
https://soramitsu.atlassian.net/browse/PW-387
=> Update history sync with subquery

package.json, src/components/mixins/LoadingMixin.ts, src/components/mixins/TransactionMixin.ts, src/index.ts, src/store/Settings.ts
https://soramitsu.atlassian.net/browse/PW-434
=> Fix rewards history & prepare LoadingMixin for export

src/components/WalletAssets.vue
=> Change paddings

package.json, src/components/WalletTransactionDetails.vue
[PW-404]: Referral system support via web app
* Referral system: fixed naming.
[PW-404]: https://soramitsu.atlassian.net/browse/PW-404
=> PW-404: Naming fix

package.json, src/services/subquery/explorer.ts, src/services/subquery/queries/referrerRewards.ts, src/services/types.ts
[PW-404]: Referral system support via web app
* Referral System: Fixed subquery
[PW-404]: https://soramitsu.atlassian.net/browse/PW-404
=> Referral System Subquery Fixes

package.json, src/services/subquery/explorer.ts, src/services/subquery/queries/fiatPriceAndApy.ts, src/services/subquery/types.ts
https://soramitsu.atlassian.net/browse/PW-576
=> Fiat prices fix

package.json, src/services/subquery/explorer.ts, src/services/subquery/queries/referrerRewards.ts
=> Referral Rewards Fix

package.json, src/App.vue, src/api/index.ts, src/components/WalletHistory.vue, src/components/WalletTransactionDetails.vue, src/components/mixins/TransactionMixin.ts, src/store/Transactions.ts, tests/unit/components/WalletHistory.spec.ts
https://soramitsu.atlassian.net/browse/PW-309
https://soramitsu.atlassian.net/browse/PW-587
=> Transaction detection improvements

package.json, src/components/QrCode.vue, src/components/QrCodeScanButton.vue, src/components/RecieveToken.vue, src/components/WalletHistory.vue, src/store/Transactions.ts
https://soramitsu.atlassian.net/browse/PW-612
=> Fix qr code reading

package.json, src/services/subquery/explorer.ts, src/services/subquery/queries/referrerRewards.ts, src/services/subquery/types.ts
https://soramitsu.atlassian.net/browse/PW-585
=> Referrer rewards groupedAggegates query

package.json, src/components/WalletAssetDetails.vue, src/components/WalletHistory.vue
=> Asset Action Shadow Fix

package.json, yarn.lock
[PW-665]: Referral Program: Add Referrer Subscription
* Increased substrate lib, wallet versions.
[PW-665]: https://soramitsu.atlassian.net/browse/PW-665
=> PW-665: Referral Program: Add Referrer Subscription

package.json, src/components/WalletAccount.vue
1. Fix wallet address copy styles
=> Fix wallet address copy styles

package.json, src/components/QrCode/QrCodeScanButton.vue, src/components/WalletAssetDetails.vue, src/components/WalletSend.vue
[PW-730]: Issue with balance subscriptions
=> fix wallet send balance

package.json, public/env.json, src/consts/index.ts, src/services/subquery/explorer.ts, src/services/subquery/queries/historyElements.ts, src/services/subquery/types.ts, src/store/account/actions.ts, src/store/account/mutations.ts, src/store/account/state.ts, src/store/account/types.ts, src/store/settings/actions.ts, src/store/settings/mutations.ts, src/store/settings/state.ts, src/store/settings/types.ts, src/store/subscriptions/actions.ts, src/store/transactions/actions.ts, src/store/transactions/mutations.ts, src/store/transactions/types.ts, src/types/history.ts
[PW-XXXX]: Title.
1. Description.
[PW-XXXX]: https://soramitsu.atlassian.net/browse/PW-XXXX
=> Remove system events subscription

package.json, src/components/HistoryPagination.vue, src/components/WalletHistory.vue, src/components/mixins/PaginationSearchMixin.ts, src/index.ts, tests/unit/components/HistoryPagination.spec.ts, tests/unit/components/__snapshots__/HistoryPagination.spec.ts.snap, tests/unit/components/__snapshots__/WalletHistory.spec.ts.snap, tests/utils/HistoryPaginationMock.ts
[PW-733]: History Pagination Component
* Added History Pagination Component, Refactored PaginationSearchMixin.
[PW-733]: https://soramitsu.atlassian.net/browse/PW-733
=> PW-733: History Pagination Component

package.json, src/components/AddAsset/AddAssetTokenTab.vue, src/components/AssetList.vue, src/components/Connection/ExtensionConnection.vue, src/components/SearchInput.vue, src/components/SelectAsset.vue, src/components/WalletAssetDetails.vue, src/components/WalletBase.vue, src/components/WalletHistory.vue, src/styles/_mixins.scss, yarn.lock
[PW-712]: Focus Refactoring
* Refactored Focus Functionality
[PW-712]: https://soramitsu.atlassian.net/browse/PW-712
=> PW-712: Focus Refactoring

src/components/CreateNftToken.vue, src/components/InfoLine.vue, src/components/TransactionHashView.vue, src/components/WalletBase.vue, tests/unit/components/__snapshots__/InfoLine.spec.ts.snap
=> Tooltip Focus Removing

src/components/Connection/ExtensionConnection.vue, src/lang/en/index.ts, src/store/account/getters.ts, src/util/index.ts
https://soramitsu.atlassian.net/browse/PW-743
=> Change extension translations

package.json, src/components/TransactionHashView.vue
I made it the same with Bridge history
=> Fix margin for single copy button

package.json, src/components/AddAsset/AddAsset.vue, src/components/CreateToken.vue, src/components/WalletAssets.vue, src/components/WalletAssetsHeadline.vue, src/components/WalletTransactionDetails.vue, src/consts/index.ts, src/lang/en/index.ts, src/services/ceres/index.ts, src/services/subquery/explorer.ts, src/store/account/actions.ts, src/store/account/mutations.ts, src/styles/_mixins.scss, tests/unit/components/__snapshots__/AddAsset.spec.ts.snap, tests/unit/components/__snapshots__/WalletAssetsHeadline.spec.ts.snap, yarn.lock
=> Fix release issues

package.json, src/services/ceres/index.ts
1. Checked infinite loading state. It shouldn't affect loading state cuz it's not used for subquery/ceres api queries & subscriptions
2. Updated ceres api endpoint
=> Fix ceres api endpoint

package.json, src/components/WalletSend.vue, tests/unit/components/__snapshots__/WalletSend.spec.ts.snap, yarn.lock
https://soramitsu.atlassian.net/browse/PW-1006
=> Remove div wrapper from WalletSend

package.json, src/components/Connection/ExtensionConnection.vue, src/components/WalletAssets.vue, src/lang/en/index.ts, src/types/common.ts
1. Add dirty hack for scrollable list of assets.
2. Update `SettingsStorageKey`
3. Update logout behavior
=> Fix release 1.13 issues

package.json, src/components/SearchInput.vue, src/store/settings/state.ts
1. Fix allow fee popup behavior
2. Fix Search focus (keep-alive)
=> Fix release issues 1.13

Jenkinsfile, jest.config.js, package.json
[DOPS-2462]: Configured test coverage.
1. Configured test coverage.
[Sonar](https://sonar.soramitsu.co.jp/dashboard?branch=feature%2FDOPS-2462%2Fsonar&id=sora2%3Asora2-wallet-web)
[DOPS-2462]: https://soramitsu.atlassian.net/browse/DOPS-2462
=> DOPS-2462 Configured test coverage

Jenkinsfile
[DOPS-2614]: Add DefectDojo.
1. Add DefectDojo.
[DOPS-2614]: https://soramitsu.atlassian.net/browse/DOPS-2614
=> DOPS-2614 Add DefectDojo

src/components/WalletAdarTxDetails.vue, src/components/WalletTransactionDetails.vue, src/components/mixins/OperationsMixin.ts, tests/unit/components/__snapshots__/WalletAdarTxDetails.spec.ts.snap, tests/utils/mock.ts
=> fixed amount symbol if user is recipient

src/components/AddressBook/Input.vue, src/store/account/mutations.ts
[PW-1282]: Make remove from address book reactive.
1. Make remove from address book reactive.
[PW-1282]: https://soramitsu.atlassian.net/browse/PW-1282
=> Make remove from address book reactive

src/components/TokenAddress.vue, src/components/shared/FormattedAddress.vue
https://soramitsu.atlassian.net/browse/PW-1283
<h3>Before</h3>
<h3>After</h3>
=> Improve token address

package.json, src/components/Account/WalletAccount.vue, src/components/AddressBook/Contact.vue, src/components/AddressBook/Input.vue, src/components/AddressBook/List.vue, src/components/TransactionHashView.vue, src/components/WalletSend.vue, src/components/WalletTransactionDetails.vue, src/index.ts, src/services/google/backup/mapper.ts, src/services/google/wallet/accounts.ts, src/services/indexer/subquery/queries/historyElements.ts, src/services/indexer/subsquid/parser.ts, src/services/indexer/subsquid/queries/historyElements.ts, src/store/account/actions.ts, src/store/account/getters.ts, src/store/account/mutations.ts, src/store/account/state.ts, src/store/settings/mutations.ts, src/store/settings/state.ts, src/types/common.ts, src/util/index.ts, tests/unit/components/__snapshots__/WalletSend.spec.ts.snap, tests/unit/components/__snapshots__/WalletTransactionDetails.spec.ts.snap, yarn.lock
https://soramitsu.atlassian.net/browse/PW-1220
https://soramitsu.atlassian.net/browse/PW-1277
https://soramitsu.atlassian.net/browse/PW-1278
https://soramitsu.atlassian.net/browse/PW-1284
https://soramitsu.atlassian.net/browse/PW-1325
=> Fix Address book & ADAR issues

package.json, src/components/mixins/NotificationMixin.ts, src/lang/en/index.ts, src/util/index.ts
https://soramitsu.atlassian.net/browse/PW-1413
=> Add reload button to extension alert

package.json, src/components/TransactionHashView.vue, src/services/indexer/subquery/parser.ts, src/services/indexer/subquery/queries/historyElements.ts, src/services/indexer/subsquid/parser.ts, src/services/indexer/subsquid/queries/historyElements.ts, src/services/indexer/types/models.ts
https://soramitsu.atlassian.net/browse/PW-1459
=> Fix transaction details "from" field

package.json, src/store/account/actions.ts, src/util/index.ts
https://soramitsu.atlassian.net/browse/PW-1518
=> Add autoreload to getWallet method

src/consts/wallets.ts
https://soramitsu.atlassian.net/browse/PW-1691
=> Fix sora wallet name

package.json
=> version_updated

package.json, src/components/AddAsset/AddAssetDetailsCard.vue, src/components/AddAsset/AddAssetNftTab.vue, src/components/AddAsset/AddAssetTokenTab.vue, tests/unit/components/__snapshots__/TransactionHashView.spec.ts.snap, yarn.lock
=> fixed_bugs

package.json, src/components/AddAsset/AddAssetDetailsCard.vue, src/components/AddAsset/AddAssetTokenTab.vue
=> fixed_add_asset_without_tests

package.json, src/types/common.ts
Adding new keys to SettingsStorageKey
Need for sideMenu feature
---
---
- Issue/Task link: _https://soramitsu.atlassian.net/browse/PW-1730_ 
---
---
---
---
=> added_keys

package.json, src/components/Connection/ConnectionView.vue, src/components/Connection/List/Extension.vue, src/components/Connection/Step/ExtensionList.vue, src/components/Connection/Step/ImportAccount.vue, src/components/shared/ExternalLink.vue, src/index.ts, src/services/google/wallet/index.ts, src/services/sorawallet/index.ts, src/services/wallet/consts.ts, src/services/wallet/index.ts, src/services/wallet/types.ts, src/services/wallet/wallet.ts, src/services/walletconnect/index.ts, src/store/account/actions.ts, src/store/account/mutations.ts, src/store/account/types.ts, src/util/account.ts, tests/unit/components/__snapshots__/InfoLine.spec.ts.snap, tests/unit/components/__snapshots__/WalletSend.spec.ts.snap, yarn.lock
- Logic from **@sora-test/wallet-connect** package is transfered to **src/services/wallet**
- This package was created as fork, to add Fearless as predefined wallet. Now we don't need it.
---
---
- Issue/Task link: [Remove @sora-test dependency in wallet](https://soramitsu.atlassian.net/browse/PW-1748)
---
---
---
---
=> Remove @sora-test dependency

package.json, src/services/wallet/index.ts, src/services/wallet/wallet.ts, src/util/account.ts
=> Fix wallet autoreload

package.json, yarn.lock
=> update js lib & ui lib

package.json, src/components/WalletAssetDetails.vue, src/components/WalletSend.vue, src/components/mixins/OperationsMixin.ts, src/consts/index.ts, src/lang/en/index.ts, src/store/account/actions.ts, src/store/account/types.ts, src/store/settings/actions.ts, src/store/settings/mutations.ts, src/store/settings/state.ts, src/store/settings/types.ts, src/store/subscriptions/actions.ts, tests/unit/components/__snapshots__/WalletSend.spec.ts.snap, yarn.lock
- _Added an ability to send tokens with vesting option_
- _Added an ability to view token details (not only XOR like it was)_
- _To allow users making vested transfers_
- _To display token details with locked balance for receivers_
---
---
- Proceed with the main vested transfer flow: enable vesting, input all params of the TX and submit it
- Try to proceed without vesting percentage
- Try to switch on/off vesting and check fees difference
- Since fee depends on the different params (percentage/vesting switched on/off) there might be issues in case user doesn't have enough fees to proceed with the TX
---
- _[Add vesting](https://github.com/sora-xor/polkaswap-exchange-web/i …
=> Add vesting transfers support & display token details

package.json, yarn.lock
=> sora-substrate-updated

package.json, src/types/common.ts
- Added key to settingsStorage
- We need this key for auto theme change
---
---
---
---
---
---
=> added_key_isThemePreference

package.json, src/components/ReceiveToken.vue, src/components/SelectAsset.vue, src/components/WalletSend.vue, src/components/mixins/QrCodeParserMixin.ts, yarn.lock
- Parse amount data from QR code (mobile wallet)
- Add amount input to "Receive by QR"
- Parse Fearless extension QR code (has account address only). Navigates to "Select asset" view
- Functional compability with mobile wallets
---
---
- Issue/Task link: [QR code incompatibility](https://soramitsu.atlassian.net/browse/PW-1773)
---
---
- 
---
---
=> Add amount input to Receive by QR code view

package.json, src/components/Account/Settings/SignatureOption.vue, src/components/WalletSend.vue, src/components/WalletTransactionDetails.vue, src/plugins/days-js-duration.ts, src/plugins/index.ts, src/services/indexer/parser.ts, src/services/indexer/subquery/queries/historyElements.ts, src/services/indexer/subsquid/queries/historyElements.ts, src/services/indexer/types/calls.ts, src/services/indexer/types/models.ts, tests/unit/components/__snapshots__/WalletTransactionDetails.spec.ts.snap, yarn.lock
- _This PR includes several improvements regarding vested transfers feature:_
- _Improve fees fetching_
- _Add vested transfer indexer support by @Nikita-Polyakov_ in #1232
- _Display TX details for Vested Transfers_
- _Translate duration for Vested Transfer_
- _To support TX history and format it for Vested Transfers_
- _To enhance the UX of Vested Transfer feature_
---
---
- _[Task link](https://github.com/sora-xor/polkaswap-exchange-web/issues/1545)_ 
---
- _Just need to make vested transfer_
---
=> Improve vested transfer

package.json, src/components/WalletSend.vue, tests/unit/components/__snapshots__/WalletSend.spec.ts.snap
- _Disable Vested Transfer for XOR token_
- _It is restricted on-chain so it should be disabled on Polkaswap as well_
---
---
- _[Issue](https://soramitsu.atlassian.net/browse/PW-1794)_ 
---
- _Vested Transfer shouldn't appear with XOR_
---
=> Disable Vested Transfer for XOR

package.json, src/components/InfoLine.vue, src/components/WalletHistory.vue, src/components/WalletTransactionDetails.vue, src/consts/index.ts, src/index.ts, src/services/indexer/parser.ts, src/services/indexer/subquery/explorer/modules/account.ts, src/services/indexer/subquery/queries/historyElements.ts, src/services/indexer/subsquid/queries/historyElements.ts, src/services/indexer/types/calls.ts, src/services/indexer/types/models.ts, src/store/transactions/actions.ts, src/store/transactions/mutations.ts, src/store/transactions/state.ts, src/store/transactions/types.ts, src/types/history.ts, tests/unit/components/__snapshots__/InfoLine.spec.ts.snap, tests/unit/components/__snapshots__/WalletTransactionDetails.spec.ts.snap
- Fix wallet history query filter (don't show history & send request, if query is not matching any criteria)
- Fix incoming transfers hanler (notifications)
- Add token icons to transactions details
- Add usd amounts to transactions details, where it is possible
- Remove unused code for eth bridge history
- Bug fixes & ui improvements
---
---
- Issue/Task link: 
https://soramitsu.atlassian.net/browse/PW-1778
https://soramitsu.atlassian.net/browse/PW-1786
---
---
- 
---
- _Add any information the reviewer should consider, especially cross-project impacts, …
=> Improve history filter

package.json, src/components/Account/Identity.vue, src/components/Account/WalletAccount.vue, src/components/AddressBook/Contact.vue, src/components/AddressBook/Input.vue, src/components/AddressBook/List.vue, src/components/WalletSend.vue, src/types/common.ts, src/util/index.ts, tests/unit/components/__snapshots__/WalletAccount.spec.ts.snap, yarn.lock
- Add Identity component with on chain data
- Show identities on WalletSend component
- Feature request to have a proof of address
---
---
- Issue/Task link: https://soramitsu.atlassian.net/browse/PW-1803
---
---
- 
---
---
=> Improve account identity

package.json, src/components/WalletSend.vue, src/components/WalletTransactionDetails.vue, src/lang/en/index.ts, src/plugins/soramitsuUI.ts, src/store/account/actions.ts, src/store/account/types.ts, tests/unit/components/__snapshots__/WalletTransactionDetails.spec.ts.snap, yarn.lock
- _I've added start unlocking date to Wallet Send and TX Details views_
- _So users will have an ability to postpone the unlocking date._
---
---
- _[As a user I'd like to select start unlocking date](https://soramitsu.atlassian.net/browse/PW-1812)_ 
---
- _Play with different dates. Time should be the same during the TX execution_
- _Check the history item after successful vested transfer TX_
---
---
=> Add start unlocking date

package.json, src/store/account/actions.ts, src/store/account/state.ts
=> Comment Ceres fiat switch

package.json, yarn.lock
=> bump version for presto
